# Generated by Django 5.2.4 on 2025-07-10 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiDomainAuthFlow",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        help_text="Nonce to bind to session for security.",
                        max_length=64,
                    ),
                ),
                (
                    "callback_uri",
                    models.URLField(
                        help_text="Callback URI to redirect back to alt domain after completion.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created on alt domain"),
                            ("RECEIVED", "Received by main domain"),
                            ("CONFIRMED", "Login confirmed by main domain"),
                            ("DENIED", "Login denied by main domain"),
                            ("COMPLETED", "Login completed on alt domain"),
                        ],
                        default="CREATED",
                        max_length=10,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Cross-domain login"),
                            ("LOGOUT", "Cross-domain logout"),
                            ("ACCOUNT_HOME", "Cross-domain account settings access"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "timestamp_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the request was created on the alt domain.",
                    ),
                ),
                (
                    "timestamp_received",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was received by the main domain.",
                        null=True,
                    ),
                ),
                (
                    "timestamp_answered",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was confirmed/denied on the main domain.",
                        null=True,
                    ),
                ),
                (
                    "timestamp_completed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the login was completed on the alt domain.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="multidomain_auth_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
